version: '3.8'

services:
  spark-app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: crypto-cdc-spark
    volumes:
      - ./processing:/app/processing  # This overrides the copied files
      - ./storage:/app/storage
    environment:
      - PYSPARK_PYTHON=python3